### ISSUE TITLE
Create lists of questions to ask each user in the user interviews

### ISSUE THREAD

**Issue by hnagri52** [pharma-box/docs#52]

**Comment by hnagri52** [comment]
@SammyRobensParadise @JJwilkin @rajwanialiya How many questions do we want?

**Comment by SammyRobensParadise** [comment]
> @SammyRobensParadise @JJwilkin @rajwanialiya How many questions do we want?
I don't have a set specific number of questions in mind. I think the first step is to determine the kinds of questions we want to ask. I think [Likert Scale](https://en.wikipedia.org/wiki/Likert_scale) questions might be the most ideal. but As a general guideline, I think we should keep the time required to complete the survey to under 3 minutes. I think we want to know how much time pharmacists actually spend doing repeat prescriptions, and whether they feel impacted at work by the busyness of the pharmacy. These are questions for pharmacists. I suspect we will actually need two sets of questions, one for "patients" and one for pharmacy staff since their pain points are probably different. I think a good place to start would be to go through some of the problems we are trying to solve and try and write questions that would give us an answer to what would solve the problem. This is different than *how* the problem would be solved since that is our job and we don't want to bias our users. Let me know if that makes sense, we can talk about it further

**Comment by rajwanialiya** [comment]
@hnagri52 hows the progress on this task?

**Comment by hnagri52** [comment]
> @hnagri52 hows the progress on this task?

I think we should wait to see what results we get from our posted surveys then come up with questions collectively as a team.

**Comment by SammyRobensParadise** [comment]
## Sample Linkedin Post
For our final engineering capstone project at the University of Waterloo,  @rajwanialiya,  @JJwilkin, @hnagri52 and I are tacking wait times at Canadian pharmacies! To help us better understand the problem space, it would mean the world to us if you took 2 minutes to fill out a short survey available here: https://forms.gle/zcXRCUiDLXHmBNur8 telling us about your experience with prescription pickup at pharmacies. By completing the survey you will be entered for a chance to win a $20.00 Tim Horton's gift card if you so choose.

Responses are scrubbed to ensure anonymity and information will be used for research purposes only. If you have any questions you can contact us directly at [srobensparadise@uwaterloo.ca](mailto:srobensparadise@uwaterloo.ca). You can also read more about our project in our [project description](https://pharma-box.github.io/docs/documents/project-description.html)
